x-commonFields:
  - &cmseditable {label: "cmseditable", name: "cmseditable", widget: "hidden", default: true}
  - &title {label: "Title", name: "title", widget: "string"}
  - &year {label: "Release Year", name: "year", widget: "number"}
  - &desc {label: "Description", name: "description", widget: "markdown", required: false}

  - &archive {
      label: "Archive Links",
      name: "archiveLinks",
      widget: "list",
      required: false,
      fields: [
        {label: Name, name: name, widget: string},
        {label: Link, name: link, widget: string}
      ]
    }

  - &price {
      label: "Price History",
      name: "priceHistory",
      widget: "list",
      required: false,
      fields: [
        {label: Date, name: date, widget: date},
        {label: Price, name: price, widget: string}
      ]
    }

  - &skus {
      label: "SKUs",
      name: "skus",
      widget: "list",
      required: false,
      field: {label: SKU, name: sku, widget: string}
    }

  - &category {
      label: "Category",
      name: "category",
      widget: "list",
      required: false,
      field: {
        widget: "select",
        required: false,
        options: [
          "Action Accessory",
          "Book",
          "Building Basics",
          "Building Set",
          "Control (RC)",
          "Control (Rok Star)",
          "Furniture",
          "Replacement Parts",
          "Rok Blocks",
          "Rokenbok RC",
          "Start Set (RC)",
          "Start Set (Rok Star)",
          "Start Set (Unique)",
          "Vehicle (RC)",
          "Vehicle (Rok Star)",
        ]
      }
    }

  - &video {label: "Video Link", name: "video", widget: "string", required: false}

  - &plans {
      label: "Plans",
      name: "plans",
      widget: "list",
      required: false,
      fields: [
        {label: Name, name: name, widget: string},
        {label: Link, name: link, widget: file}
      ]
    }

  - &thumb {label: "Thumbnail", name: "thumb", widget: "image", required: false}

  - &images {
      label: "Images",
      name: "images",
      widget: "list",
      required: false,
      field: {label: Image, name: img, widget: image}
    }

  - &body {label: "Body", name: "body", widget: "markdown", required: false}

backend:
  name: git-gateway

media_folder: "site/static/cms" # Folder where user uploaded files should go
public_folder: "/cms"

collections: # A list of collections the CMS should be able to edit
  - name: "set" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Sets" # Used in the UI, ie.: "New Post"
    folder: "site/content/set" # The path to the folder where the documents are stored
    filter: {field: "cmseditable", value: true}
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - *cmseditable
      - *title
      - *year
      - *desc
      - *archive
      - *price
      - *skus
      - *category
      - *video
      - *plans
      - *images
      - *thumb
      - *body
  - name: "part" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Parts" # Used in the UI, ie.: "New Post"
    folder: "site/content/part" # The path to the folder where the documents are stored
    filter: {field: "cmseditable", value: true}
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - *cmseditable
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - *title
      - *year
      - *desc
      - *archive
      - *price
      - *skus
      - *category
      - *video
      - *plans
      - *images
      - *thumb
      - *body
  - name: "project" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Projects" # Used in the UI, ie.: "New Post"
    folder: "site/content/project" # The path to the folder where the documents are stored
    filter: {field: "cmseditable", value: true}
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - *cmseditable
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - *title
      - {label: Date, name: date, widget: date}
      - *desc
      - *thumb
      - *body
      - {label: "Authors", name: "authors", widget: "string"}
  
