backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "sets" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Sets" # Used in the UI, ie.: "New Post"
    folder: "site/content/set" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Release Year", name: "year", widget: "number"}
      - {label: "Description", name: "description", widget: "markdown"}

      # - label: "Archive Links"
      #   name: "archiveLinks"
      #   widget: ""

      # - label: "Price History"
      #   name: "priceHistory"
      #   widget: ""

      - label: "SKUs"
        name: "skus"
        widget: "list"
        field: {label: SKU, name: sku, widget: text}

      # - label: "Category"
      #   name: "category"
      #   widget: ""

      # - label: "Video Link"
      #   name: "video"
      #   widget: ""

      # - label: "Plans"
      #   name: "plans"
      #   widget: ""


      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  