backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "sets" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Sets" # Used in the UI, ie.: "New Post"
    folder: "site/content/set" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Release Year", name: "year", widget: "number"}
      - {label: "Description", name: "description", widget: "markdown", required: false}

      - label: "Archive Links"
        name: "archiveLinks"
        widget: "list"
        required: false
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Link, name: link, widget: string}

      - label: "Price History"
        name: "priceHistory"
        widget: "list"
        required: false
        fields:
          - {label: Date, name: date, widget: date}
          - {label: Price, name: price, widget: string}

      - label: "SKUs"
        name: "skus"
        widget: "list"
        required: false
        field: {label: SKU, name: sku, widget: string}

      - label: "Category"
        name: "category"
        widget: "select"
        required: false
        options: 
          - Action Accessory
          - Book
          - Building Basics
          - Building Set
          - Control (RC)
          - Control (Rok Star)
          - Furniture
          - Rok Blocks
          - Rokenbok RC
          - Start Set (RC)
          - Start Set (Rok Star)
          - Start Set (Unique)
          - Vehicle (RC)
          - Vehicle (Rok Star)

      - label: "Video Link"
        name: "video"
        widget: "string"
        required: false

      - label: "Plans"
        name: "plans"
        widget: "list"
        required: false
        fields:
          - {label: Name, name: name, widget: string}
          - {label: Link, name: link, widget: string}

      - label: "Thumbnail"
        name: "thumb"
        widget: "image"
        required: false
        widget: image

      - label: "Images"
        name: "images"
        widget: "list"
        required: false
        field: {label: Image, name: img, widget: image}


      - {label: "Body", name: "body", widget: "markdown", required: false}
  